---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
require(doParallel)
```

```{r}
cores_2_use <- detectCores() - 1
cl <- makeCluster(cores_2_use)
clusterSetRNGStream(cl, 2344)
registerDoParallel(cl)

g <- foreach(i = 1:30000, .combine = c) %dopar% {
 median(rnorm(1000))  
}
stopCluster(cl)
```

```{r}
curve(dgamma(x,shape = 3,scale=2),0,20)
test <- seq(10,15,by = 0.01)
for (i in seq_along(test))
{
  uniroot(f,x1=test[i],target = 0.95,c(0.20))
}

f <- function(x1,x2,target) pgamma(x1,shape = 3,scale=2) - pgamma(x2,shape=3,scale=2) - target
ui <- uniroot(f,x1=test,target = 0.95,c(0,20))
ui$root
```

In class
```{r}
d <- 0.08
xxx <- seq(0,25,by=0.01)
mode <- xxx[which.max(dgamma(xxx,shape =3,scale =2))]
abline(h=d)
abline(v=mode)

one_d <- function(d)
{
  xxx <- seq(0,25,by=0.01)
  mode <- xxx[which.max(dgamma(xxx,shape =3,scale =2))] 
  x1 <- uniroot(function(x,d) {dgamma(x,shape = 3,scale=2)-d},c(0,mode),d=d)$ root
  x2 <- uniroot(function(x,d) {dgamma(x,shape = 3,scale=2)-d},c(mode,25),d=d)$root
  is <- pgamma(x2,shape=3,scale =2) -pgamma(x1,shape=3,scale =2)
  list(x1=x1,x2=x2,is=is)
}
one_d(0.04)

many_d <- function(ds)
{
  out <- ds*0
  for (i in seq_along(ds))
  {
    out[i] <- one_d(ds[i]) $is
  }
  out
}
many_d(c(0.01,0.02,0.03))

uniroot(function(d,is){many_d(d) - is},c(0.01,0.12),is=.95)
one_d(0.01700347)

HDInterval::hdi(rgamma(10000000,shape=3,scale=2))
```

```{r}

```

