---
title: "Eda_Final_cor_Peter"
author: "Zhengqi Tian"
date: "11/18/2021"
output: github_document
---


```{r}
library(ggdemetra)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggcorrplot)
```

```{r}

data <- read_csv("Energy Census and Economic Data US 2010-2014 copy.csv")

```

```{r}
head(data)
```
# Consumption
```{r}
#Generate an 2010 Consumption data table including all related columns
Consumption2010<-data%>%
  select("TotalC2010","BiomassC2010","CoalC2010","ElecC2010","FossFuelC2010","GeoC2010","HydroC2010","NatGasC2010","LPGC2010","GDP2010")
Consumption2010

#Generate an 2011 Consumption data table including all related columns
Consumption2011<-data%>%
  select("TotalC2011","BiomassC2011","CoalC2011","ElecC2011","FossFuelC2011","GeoC2011","HydroC2011","NatGasC2011","LPGC2011","GDP2011")
Consumption2011

#Generate an 2012 Consumption data table including all related columns
Consumption2012<-data%>%
  select("TotalC2012","BiomassC2012","CoalC2012","ElecC2012","FossFuelC2012","GeoC2012","HydroC2012","NatGasC2012","LPGC2012","GDP2012")
Consumption2012

#Generate an 2013 Consumption data table including all related columns
Consumption2013<-data%>%
  select("TotalC2013","BiomassC2013","CoalC2013","ElecC2013","FossFuelC2013","GeoC2013","HydroC2013","NatGasC2013","LPGC2013","GDP2013")
Consumption2013

#Generate an 2014 Consumption data table including all related columns
Consumption2014<-data%>%
  select("TotalC2014","BiomassC2014","CoalC2014","ElecC2014","FossFuelC2014","GeoC2014","HydroC2014","NatGasC2014","LPGC2014","GDP2014")
Consumption2014

```

```{r}
#Visualization
#Consumption2010
# Compute a correlation matrix
corr2010 <- round(cor(Consumption2010), 1)
# Compute a matrix of correlation p-values
p.mat2010 <- cor_pmat(Consumption2010)
# Visualize the correlation matrix
corrplot2010<-ggcorrplot(corr2010, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   legend.title = "Correlation",
   p.mat = p.mat2010,
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2010

#Consumption2011
# Compute a correlation matrix
corr2011 <- round(cor(Consumption2011), 1)
# Compute a matrix of correlation p-values
p.mat2011 <- cor_pmat(Consumption2011)
# Visualize the correlation matrix
corrplot2011<-ggcorrplot(corr2011, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   legend.title = "Correlation",
   p.mat = p.mat2011,
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2011


# Compute a correlation matrix
corr2012 <- round(cor(Consumption2012), 1)
# Compute a matrix of correlation p-values
p.mat2012 <- cor_pmat(Consumption2012)
# Visualize the correlation matrix
corrplot2012<-ggcorrplot(corr2012, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   legend.title = "Correlation",
   p.mat = p.mat2012,
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2012

# Compute a correlation matrix
corr2013 <- round(cor(Consumption2013), 1)
# Compute a matrix of correlation p-values
p.mat2013 <- cor_pmat(Consumption2013)
# Visualize the correlation matrix
corrplot2013<-ggcorrplot(corr2013, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   legend.title = "Correlation",
   p.mat = p.mat2013,
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2013

# Compute a correlation matrix
corr2014 <- round(cor(Consumption2014), 1)
# Compute a matrix of correlation p-values
p.mat2014 <- cor_pmat(Consumption2014)
# Visualize the correlation matrix
corrplot2014<-ggcorrplot(corr2014, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   legend.title = "Correlation",
   p.mat = p.mat2014,
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2014

ggarrange( corrplot2010, corrplot2012,corrplot2013, corrplot2014,
            labels = c("Correlation_2011", "Correlation_2012", "Correlation_2013","Correlation_2014"),
            ncol = 2, nrow = 2,
            legend = "right")
```

# Production
```{r}
#Generate an 2010 Production data table including all related columns
Production2010<-data%>%
  select("TotalP2010","CoalC2010","GeoP2010","HydroP2010","NatGasC2010","LPGC2010","GDP2010")
Production2010

#Generate an 2011 Production data table including all related columns
Production2011<-data%>%
  select("TotalP2011","CoalC2011","GeoP2011","HydroP2011","NatGasC2011","LPGC2011","GDP2011")
Production2011

#Generate an 2012 Production data table including all related columns
Production2012<-data%>%
  select("TotalP2012","CoalC2012","GeoP2012","HydroP2012","NatGasC2012","LPGC2012","GDP2012")
Production2012

#Generate an 2013 Production data table including all related columns
Production2013<-data%>%
  select("TotalP2013","CoalC2013","GeoP2013","HydroP2013","NatGasC2013","LPGC2013","GDP2013")
Production2013

#Generate an 2014 Production data table including all related columns
Production2014<-data%>%
  select("TotalP2014","CoalC2014","GeoP2014","HydroP2014","NatGasC2014","LPGC2014","GDP2014")
Production2014

```
```{r}
#Visualization
#Production2010
# Compute a correlation matrix
corr2010 <- round(cor(Production2010), 1)
# Compute a matrix of correlation p-values
p.mat2010 <- cor_pmat(Production2010)
# Visualize the correlation matrix
corrplot2010<-ggcorrplot(corr2010, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2010,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2010

#Production2011
# Compute a correlation matrix
corr2011 <- round(cor(Production2011), 1)
# Compute a matrix of correlation p-values
p.mat2011 <- cor_pmat(Production2011)
# Visualize the correlation matrix
corrplot2011<-ggcorrplot(corr2011, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2011,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2011


# Compute a correlation matrix
corr2012 <- round(cor(Production2012), 1)
# Compute a matrix of correlation p-values
p.mat2012 <- cor_pmat(Production2012)
# Visualize the correlation matrix
corrplot2012<-ggcorrplot(corr2012, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2012,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2012

# Compute a correlation matrix
corr2013 <- round(cor(Production2013), 1)
# Compute a matrix of correlation p-values
p.mat2013 <- cor_pmat(Production2013)
# Visualize the correlation matrix
corrplot2013<-ggcorrplot(corr2013, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2013,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2013

# Compute a correlation matrix
corr2014 <- round(cor(Production2014), 1)
# Compute a matrix of correlation p-values
p.mat2014 <- cor_pmat(Production2014)
# Visualize the correlation matrix
corrplot2014<-ggcorrplot(corr2014, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2014,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2014

ggarrange( corrplot2010, corrplot2012,corrplot2013, corrplot2014,
            labels = c("Correlation_2011", "Correlation_2012", "Correlation_2013","Correlation_2014"),
            ncol = 2, nrow = 2,
            legend = "right")
```

# Earning
```{r}
#Generate an 2010 Earning data table including all related columns
Earning2010<-data%>%
  select("TotalE2010","CoalE2010","ElecE2010","NatGasE2010","LPGE2010","GDP2010")
Earning2010

#Generate an 2011 Earning data table including all related columns
Earning2011<-data%>%
  select("TotalE2011","CoalE2011","ElecE2011","NatGasE2011","LPGE2011","GDP2011")
Earning2011

#Generate an 2012 Earning data table including all related columns
Earning2012<-data%>%
  select("TotalE2012","CoalE2012","ElecE2012","NatGasE2012","LPGE2012","GDP2012")
Earning2012

#Generate an 2013 Earning data table including all related columns
Earning2013<-data%>%
  select("TotalE2013","CoalE2013","ElecE2013","NatGasE2013","LPGE2013","GDP2013")
Earning2013

#Generate an 2014 Earning data table including all related columns
Earning2014<-data%>%
  select("TotalE2014","CoalE2014","ElecE2014","NatGasE2014","LPGE2014","GDP2014")
Earning2014

```

```{r}
#Visualization
#Earning2010
# Compute a correlation matrix
corr2010 <- round(cor(Earning2010), 1)
# Compute a matrix of correlation p-values
p.mat2010 <- cor_pmat(Earning2010)
# Visualize the correlation matrix
corrplot2010<-ggcorrplot(corr2010, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2010,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2010

#Earning2011
# Compute a correlation matrix
corr2011 <- round(cor(Earning2011), 1)
# Compute a matrix of correlation p-values
p.mat2011 <- cor_pmat(Earning2011)
# Visualize the correlation matrix
corrplot2011<-ggcorrplot(corr2011, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2011,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2011


# Compute a correlation matrix
corr2012 <- round(cor(Earning2012), 1)
# Compute a matrix of correlation p-values
p.mat2012 <- cor_pmat(Earning2012)
# Visualize the correlation matrix
corrplot2012<-ggcorrplot(corr2012, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2012,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2012

# Compute a correlation matrix
corr2013 <- round(cor(Earning2013), 1)
# Compute a matrix of correlation p-values
p.mat2013 <- cor_pmat(Earning2013)
# Visualize the correlation matrix
corrplot2013<-ggcorrplot(corr2013, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2013,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2013

# Compute a correlation matrix
corr2014 <- round(cor(Earning2014), 1)
# Compute a matrix of correlation p-values
p.mat2014 <- cor_pmat(Earning2014)
# Visualize the correlation matrix
corrplot2014<-ggcorrplot(corr2014, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2014,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2014

ggarrange( corrplot2010, corrplot2012,corrplot2013, corrplot2014,
            labels = c("Correlation_2011", "Correlation_2012", "Correlation_2013","Correlation_2014"),
            ncol = 2, nrow = 2,
            legend = "right")
```
```{r}
head(data)
```
# Price
```{r}
#Generate an 2010 Price data table including all related columns
Price2010<-data%>%
  select("TotalPrice2010","CoalPrice2010","ElecPrice2010","NatGasPrice2010","LPGPrice2010","GDP2010")
Price2010

#Generate an 2011 Price data table including all related columns
Price2011<-data%>%
  select("TotalPrice2011","CoalPrice2011","ElecPrice2011","NatGasPrice2011","LPGPrice2011","GDP2011")
Price2011

#Generate an 2012 Price data table including all related columns
Price2012<-data%>%
  select("TotalPrice2012","CoalPrice2012","ElecPrice2012","NatGasPrice2012","LPGPrice2012","GDP2012")
Price2012

#Generate an 2013 Price data table including all related columns
Price2013<-data%>%
  select("TotalPrice2013","CoalPrice2013","ElecPrice2013","NatGasPrice2013","LPGPrice2013","GDP2013")
Price2013

#Generate an 2014 Price data table including all related columns
Price2014<-data%>%
  select("TotalPrice2014","CoalPrice2014","ElecPrice2014","NatGasPrice2014","LPGPrice2014","GDP2014")
Price2014

```

```{r}
#Visualization
#Price2010
# Compute a correlation matrix
corr2010 <- round(cor(Price2010), 1)
# Compute a matrix of correlation p-values
p.mat2010 <- cor_pmat(Price2010)
# Visualize the correlation matrix
corrplot2010<-ggcorrplot(corr2010, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2010,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2010

#Price2011
# Compute a correlation matrix
corr2011 <- round(cor(Price2011), 1)
# Compute a matrix of correlation p-values
p.mat2011 <- cor_pmat(Price2011)
# Visualize the correlation matrix
corrplot2011<-ggcorrplot(corr2011, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2011,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2011


# Compute a correlation matrix
corr2012 <- round(cor(Price2012), 1)
# Compute a matrix of correlation p-values
p.mat2012 <- cor_pmat(Price2012)
# Visualize the correlation matrix
corrplot2012<-ggcorrplot(corr2012, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2012,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2012

# Compute a correlation matrix
corr2013 <- round(cor(Price2013), 1)
# Compute a matrix of correlation p-values
p.mat2013 <- cor_pmat(Price2013)
# Visualize the correlation matrix
corrplot2013<-ggcorrplot(corr2013, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2013,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2013

# Compute a correlation matrix
corr2014 <- round(cor(Price2014), 1)
# Compute a matrix of correlation p-values
p.mat2014 <- cor_pmat(Price2014)
# Visualize the correlation matrix
corrplot2014<-ggcorrplot(corr2014, type = "lower",
   outline.col = "white",
   hc.order = TRUE,
   p.mat = p.mat2014,
   legend.title = "Correlation",
   lab = TRUE,
   ggtheme = ggplot2::theme_gray,
   method="circle")
corrplot2014

ggarrange( corrplot2010, corrplot2012,corrplot2013, corrplot2014,
            labels = c("Correlation_2011", "Correlation_2012", "Correlation_2013","Correlation_2014"),
            ncol = 2, nrow = 2,
            legend = "right")
```


